/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kamus;

import java.awt.EventQueue;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;


/**
 *
 * @author TOSHIBA
 */
public class menuutama_1 extends javax.swing.JFrame {
    ArrayList name = new ArrayList();
    
    public menuutama_1() {
        initComponents();
        DatabaseNama();
        DbJcb();
        AutoCompleteDecorator.decorate(combokata);

    }

public void ClosingFrame(){
    WindowEvent winClossingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClossingEvent);
}
    
private void DbJcb(){
    try{
            String sql = "SELECT * FROM klinis;";
            
            String url = "jdbc:mysql://localhost:3306/psikologi";
            java.sql.Connection conn =(Connection)Kamus.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()){
                combokata.addItem(res.getString("kata_istilah"));
            }
            res.close();
            stm.close();
            conn.close();
            
        }catch(SQLException e){
    
            }
    
}

private void DatabaseNama(){
    try{
            String sql = "SELECT * FROM klinis;";
            
            String url = "jdbc:mysql://localhost:3306/psikologi";
            java.sql.Connection conn =(Connection)Kamus.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()){
                String Nama = res.getString("kata_istilah");
                name.add(Nama);
            }
            res.close();
            stm.close();
            conn.close();
            
        }catch(SQLException e){
    
            }
}

public void autoComplete (String txt){
    String complete = "";
    int start = txt.length();
    int last = txt.length();
    int a;
    for (a=0; a<name.size();a++){
        if (name.get(a).toString().startsWith(txt)){
            complete = name.get(a).toString();
            last = complete.length();
            break;
        }
    }
    if (last>start){
        kata.setText(complete);
        kata.setCaretPosition(last);
        kata.moveCaretPosition(start);
        
    }
}
    



    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodymenu = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        judul1 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        iconpsikologi = new javax.swing.JLabel();
        btnistilah = new javax.swing.JButton();
        btninformasi = new javax.swing.JButton();
        btnadmin = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        isimenu = new javax.swing.JPanel();
        istilah = new javax.swing.JPanel();
        judulistilah = new javax.swing.JLabel();
        kata = new javax.swing.JTextField();
        arti = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        combokata = new javax.swing.JComboBox<>();
        informasi = new javax.swing.JPanel();
        informasipsikologi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        isiiformasi = new javax.swing.JTextArea();
        admin = new javax.swing.JPanel();
        judullogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        juduluser = new javax.swing.JLabel();
        judulpass = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        menu.setBackground(new java.awt.Color(102, 102, 102));
        menu.setForeground(new java.awt.Color(153, 153, 153));

        judul1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        judul1.setForeground(new java.awt.Color(255, 255, 255));
        judul1.setText("KAMUS");

        judul2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        judul2.setForeground(new java.awt.Color(255, 255, 255));
        judul2.setText("Istilah Psikologi Klinis");

        iconpsikologi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kamus/Gambar/icons8-psychology-80.png"))); // NOI18N

        btnistilah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnistilah.setText("Istilah Psikologi Klinis");
        btnistilah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnistilahActionPerformed(evt);
            }
        });

        btninformasi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btninformasi.setText("Informasi Psikologi");
        btninformasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninformasiActionPerformed(evt);
            }
        });

        btnadmin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnadmin.setText("Admin");
        btnadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminActionPerformed(evt);
            }
        });

        btnkeluar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnistilah))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(judul2))
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(judul1))
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(iconpsikologi))
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btninformasi))
                            .addGroup(menuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnadmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnkeluar)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(judul1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul2)
                .addGap(11, 11, 11)
                .addComponent(iconpsikologi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnistilah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btninformasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadmin)
                    .addComponent(btnkeluar))
                .addContainerGap())
        );

        isimenu.setBackground(new java.awt.Color(204, 204, 204));
        isimenu.setLayout(new java.awt.CardLayout());

        judulistilah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        judulistilah.setText("Istilah Psikologi Klinis");

        kata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kataActionPerformed(evt);
            }
        });
        kata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kataKeyPressed(evt);
            }
        });

        arti.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        arti.setAutoscrolls(false);
        arti.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btncari.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btncari.setText("SEARCH");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        combokata.setEditable(true);
        combokata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        combokata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combokataActionPerformed(evt);
            }
        });
        combokata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combokataKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout istilahLayout = new javax.swing.GroupLayout(istilah);
        istilah.setLayout(istilahLayout);
        istilahLayout.setHorizontalGroup(
            istilahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(istilahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(istilahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(istilahLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(arti))
                    .addGroup(istilahLayout.createSequentialGroup()
                        .addGroup(istilahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judulistilah)
                            .addGroup(istilahLayout.createSequentialGroup()
                                .addGroup(istilahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(combokata, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kata, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncari)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        istilahLayout.setVerticalGroup(
            istilahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(istilahLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(judulistilah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combokata, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(istilahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kata, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arti, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        isimenu.add(istilah, "card2");

        informasipsikologi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        informasipsikologi.setText("Informasi Psikologi");

        isiiformasi.setColumns(20);
        isiiformasi.setRows(5);
        isiiformasi.setText("Psikologi adalah ilmu yang luas dan ambisius. \nIlmu yang dilengkapi oleh biologi dan ilmu saraf.\nPada perbatasannya dengan ilmu alam dan \ndilengkapi oleh sosiologi dan anthropologi pada \nperbatasannya dengan ilmu social \n(Bayu Lebond, 2017).");
        jScrollPane1.setViewportView(isiiformasi);

        javax.swing.GroupLayout informasiLayout = new javax.swing.GroupLayout(informasi);
        informasi.setLayout(informasiLayout);
        informasiLayout.setHorizontalGroup(
            informasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informasiLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(informasipsikologi)
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(informasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        informasiLayout.setVerticalGroup(
            informasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informasipsikologi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        isimenu.add(informasi, "card3");

        judullogin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        judullogin.setText("LOGIN");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kamus/Gambar/gambar login.png"))); // NOI18N

        user.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        juduluser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        juduluser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kamus/Gambar/username.png"))); // NOI18N
        juduluser.setText("Username");

        judulpass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        judulpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kamus/Gambar/password.png"))); // NOI18N
        judulpass.setText("Password");

        btnlogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnlogin.setText("LOGIN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminLayout = new javax.swing.GroupLayout(admin);
        admin.setLayout(adminLayout);
        adminLayout.setHorizontalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(judullogin))
                    .addGroup(adminLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(judulpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(juduluser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                            .addComponent(pass)))
                    .addGroup(adminLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btnlogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminLayout.setVerticalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(judullogin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(juduluser)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judulpass)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnlogin)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        isimenu.add(admin, "card4");

        javax.swing.GroupLayout bodymenuLayout = new javax.swing.GroupLayout(bodymenu);
        bodymenu.setLayout(bodymenuLayout);
        bodymenuLayout.setHorizontalGroup(
            bodymenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodymenuLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isimenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodymenuLayout.setVerticalGroup(
            bodymenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(isimenu, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodymenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodymenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnistilahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnistilahActionPerformed
        //hapus
        isimenu.removeAll();
        isimenu.repaint();
        isimenu.revalidate();
        
        //panggil
        isimenu.add(istilah);
        isimenu.repaint();
        isimenu.revalidate();
        
    }//GEN-LAST:event_btnistilahActionPerformed

    private void btninformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninformasiActionPerformed
        // hapus
        isimenu.removeAll();
        isimenu.repaint();
        isimenu.revalidate();
        
        //panggil
        isimenu.add(informasi);
        isimenu.repaint();
        isimenu.revalidate();
    }//GEN-LAST:event_btninformasiActionPerformed

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminActionPerformed
        // TODO add your handling code here:
        isimenu.removeAll();
        isimenu.repaint();
        isimenu.revalidate();
        
        //panggil
        isimenu.add(admin);
        isimenu.repaint();
        isimenu.revalidate();
    }//GEN-LAST:event_btnadminActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        
        try{
            String sql = "SELECT kata_istilah , arti_istilah FROM klinis WHERE kata_istilah LIKE '"+combokata.getSelectedItem()+"'";
            
            String url = "jdbc:mysql://localhost/psikologi";
            java.sql.Connection conn =(Connection)Kamus.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                arti.setText(res.getString("arti_istilah"));
            }
           
        }catch(SQLException e){
          JOptionPane.showMessageDialog(null, e);  
        }
        
    }//GEN-LAST:event_btncariActionPerformed

    private void kataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kataActionPerformed

    private void kataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kataKeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_ENTER:
                kata.setText(kata.getText());
//                jComboBox1.getSelectedItem();
                break;
            default:
                EventQueue.invokeLater(new Runnable(){
            @Override
            public void run() {
                String txt = kata.getText();
                autoComplete(txt);
            }
                });
    }
    }//GEN-LAST:event_kataKeyPressed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed
    // TODO add your handling code here:


    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void combokataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combokataKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_combokataKeyPressed

    private void combokataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combokataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combokataActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        try{
            String username = user.getText();
            String password = pass.getText();
            
            String sql = "SELECT * FROM admin WHERE username=? and pass=?";
            
            String url = "jdbc:mysql://localhost/psikologi";
            java.sql.Connection conn =(Connection)Kamus.configDB();
            PreparedStatement stm = conn.prepareStatement(sql);
//            java.sql.Statement stm = conn.createStatement();
//            java.sql.ResultSet res = stm.executeQuery(sql);
            stm.setString(1, username);
            stm.setString(2, password);
            
            ResultSet set = stm.executeQuery();
            if (set.next()){
                JOptionPane.showMessageDialog(null, "login success");
                ClosingFrame();
                menuadmin admin = new menuadmin();
                admin.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Incorrect username or password");
            }
        }catch(SQLException e){
          JOptionPane.showMessageDialog(null, e);  
        }
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin;
    private javax.swing.JTextField arti;
    private javax.swing.JPanel bodymenu;
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btninformasi;
    private javax.swing.JButton btnistilah;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnlogin;
    private javax.swing.JComboBox<String> combokata;
    private javax.swing.JLabel iconpsikologi;
    private javax.swing.JPanel informasi;
    private javax.swing.JLabel informasipsikologi;
    private javax.swing.JTextArea isiiformasi;
    private javax.swing.JPanel isimenu;
    private javax.swing.JPanel istilah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judulistilah;
    private javax.swing.JLabel judullogin;
    private javax.swing.JLabel judulpass;
    private javax.swing.JLabel juduluser;
    public javax.swing.JTextField kata;
    private javax.swing.JPanel menu;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
