/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kamus;

import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author TOSHIBA
 */
public class menuadmin extends javax.swing.JFrame {
    
    //kosongkanform
    
    private void kosongkan_form(){
        idpsikologi.setEditable(true);
        idpsikologi.setText(null);
        kataistilah.setText(null);
        artiistilah.setText(null);
   
    }
    
    //tampilkan data
    
    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Id Psikologi");
        model.addColumn("Kata Istilah Psikologi Klinis");
        model.addColumn("Arti Istilah Psikologi Klinis");
        
        try{
            int no = 1;
            String sql = "SELECT * FROM klinis";
            java.sql.Connection conn =(Connection)Kamus.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3)});
                
            }
            tableistilah.setModel(model);
            
        }catch (SQLException e){
            System.out.println("Error: " + e.getMessage());
        }
        
    }

    /**
     * Creates new form menuadmin
     */
    public menuadmin() {
        initComponents();
        tampilkan_data();
        kosongkan_form();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin = new javax.swing.JPanel();
        judulhalaman = new javax.swing.JLabel();
        gambaradmin = new javax.swing.JLabel();
        btnpsikologi = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        halamanadmin = new javax.swing.JPanel();
        isiistilah = new javax.swing.JPanel();
        judulhalamankerja = new javax.swing.JLabel();
        judulid = new javax.swing.JLabel();
        idpsikologi = new javax.swing.JTextField();
        judulkata = new javax.swing.JLabel();
        kataistilah = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        artiistilah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableistilah = new javax.swing.JTable();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        admin.setBackground(new java.awt.Color(153, 153, 153));

        judulhalaman.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        judulhalaman.setForeground(new java.awt.Color(255, 255, 255));
        judulhalaman.setText("HALAMAN ADMIN");

        gambaradmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kamus/Gambar/admin.png"))); // NOI18N

        btnpsikologi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnpsikologi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kamus/Gambar/icons8-news-30.png"))); // NOI18N
        btnpsikologi.setText("Istilah Psikologi Klinis");
        btnpsikologi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpsikologiActionPerformed(evt);
            }
        });

        btnlogout.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kamus/Gambar/login.png"))); // NOI18N
        btnlogout.setText("LOG OUT");

        javax.swing.GroupLayout adminLayout = new javax.swing.GroupLayout(admin);
        admin.setLayout(adminLayout);
        adminLayout.setHorizontalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnlogout))
                    .addGroup(adminLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(gambaradmin))
                    .addComponent(btnpsikologi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(adminLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(judulhalaman)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        adminLayout.setVerticalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(judulhalaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gambaradmin)
                .addGap(110, 110, 110)
                .addComponent(btnpsikologi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addGap(23, 23, 23))
        );

        halamanadmin.setLayout(new java.awt.CardLayout());

        judulhalamankerja.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        judulhalamankerja.setText("HALAMAN KERJA ADMIN");

        judulid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        judulid.setText("Id Psikologi ");

        idpsikologi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        judulkata.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        judulkata.setText("Kata Istilah");

        kataistilah.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Arti Istilah");

        artiistilah.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tableistilah.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tableistilah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Psikologi", "Kata Istilah Psikologi Klinis", "Arti Istilah Psikologi Klinis"
            }
        ));
        tableistilah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableistilahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableistilah);

        btnsimpan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnkeluar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout isiistilahLayout = new javax.swing.GroupLayout(isiistilah);
        isiistilah.setLayout(isiistilahLayout);
        isiistilahLayout.setHorizontalGroup(
            isiistilahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiistilahLayout.createSequentialGroup()
                .addGroup(isiistilahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isiistilahLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(isiistilahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(isiistilahLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(artiistilah)))
                    .addGroup(isiistilahLayout.createSequentialGroup()
                        .addGroup(isiistilahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(isiistilahLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(judulid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idpsikologi, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(isiistilahLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(judulkata)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kataistilah, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(isiistilahLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(judulhalamankerja)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(isiistilahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsimpan)
                .addGap(74, 74, 74)
                .addComponent(btnedit)
                .addGap(89, 89, 89)
                .addComponent(btnhapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnkeluar)
                .addGap(56, 56, 56))
        );
        isiistilahLayout.setVerticalGroup(
            isiistilahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiistilahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulhalamankerja)
                .addGap(18, 18, 18)
                .addGroup(isiistilahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judulid)
                    .addComponent(idpsikologi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(isiistilahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judulkata)
                    .addComponent(kataistilah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artiistilah, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(isiistilahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnedit)
                    .addComponent(btnhapus)
                    .addComponent(btnkeluar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        halamanadmin.add(isiistilah, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(halamanadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(halamanadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpsikologiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpsikologiActionPerformed
        // TODO add your handling code here:
        //hapus
        halamanadmin.removeAll();
        halamanadmin.repaint();
        halamanadmin.revalidate();
        
        //panggil
        halamanadmin.add(isiistilah);
        halamanadmin.repaint();
        halamanadmin.revalidate();
    }//GEN-LAST:event_btnpsikologiActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "Insert Into klinis VALUES('"+idpsikologi.getText()+"','"+kataistilah.getText()+"','"+artiistilah.getText()+"')";
            java.sql.Connection conn = (Connection)Kamus.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Simpan Data Berhasil");
            tampilkan_data();
            kosongkan_form();
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void tableistilahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableistilahMouseClicked
        // TODO add your handling code here:
        int baris = tableistilah.rowAtPoint(evt.getPoint());
        String id_psikologi = tableistilah.getValueAt(baris, 1).toString();
        idpsikologi.setText(id_psikologi);
        
        String kata_istilah = tableistilah.getValueAt(baris, 2).toString();
        kataistilah.setText(kata_istilah);
        
        String arti_istilah = tableistilah.getValueAt(baris, 3).toString();
        artiistilah.setText(arti_istilah);
        
        
        
    }//GEN-LAST:event_tableistilahMouseClicked

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try{
          String sql = "UPDATE klinis SET id_psikologi ='"+idpsikologi.getText()+"',kata_istilah='"+kataistilah.getText()+"',arti_istilah='"+artiistilah.getText()+"'WHERE id_psikologi ='"+idpsikologi.getText()+"'";
          java.sql.Connection conn = (Connection)Kamus.configDB();
          java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
          pstm.execute();
          JOptionPane.showMessageDialog(null,"Edit Data Berhasil");
                  }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
                  }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try{
          String sql = "DELETE FROM klinis Where id_psikologi='"+idpsikologi.getText()+"'";
          java.sql.Connection conn = (Connection)Kamus.configDB();
          java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
          pstm.execute();
          JOptionPane.showMessageDialog(null,"Hapus Data Berhasil");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
           }
        tampilkan_data();
        kosongkan_form();
        
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin;
    private javax.swing.JTextField artiistilah;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnpsikologi;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel gambaradmin;
    private javax.swing.JPanel halamanadmin;
    private javax.swing.JTextField idpsikologi;
    private javax.swing.JPanel isiistilah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulhalaman;
    private javax.swing.JLabel judulhalamankerja;
    private javax.swing.JLabel judulid;
    private javax.swing.JLabel judulkata;
    private javax.swing.JTextField kataistilah;
    private javax.swing.JTable tableistilah;
    // End of variables declaration//GEN-END:variables
}
